### PR TITLE
handle the case when no typeRow is defined

### LINKED ISSUE #97: support fetching from other shimo tables outside of wuhan2020
## 描述功能要求
https://shimo.im/sheets/qZx7ltnDo0I9BSLD/8U70d, which is a table about a non-profit program.
To fetch the table data to github without changing the table itself. The code base should be slightly modified.

### PR DESCRIPTION
**Pull request by zhaofeng-shu33**
## Purpose | 本PR解决的问题

Currently the code needs typeRow , which is missing in tables of other organizations. We need 
 supporting the definition the type of table column in schema file?
- Closes #97

## Changes | 本PR的更改

switch in `types` definition.

### Checklist | 检查

* **Are tests written for added code? | 新增代码是否添加测试用例**

- [ ] Yes
- [x] No because:
 non-yet
* **Did you introduce any new dependencies? | 如果添加新的依赖，请列出依赖并说明添加该依赖的原因**

- [x] No
- [ ] Yes
  - Dependency:
  - Reason:

Bypassing husky check since husky does not support the git prior to 2.0 and the git of my workstation is a little bit old.

### CODE REVIEW

**Review by frank-zsy — APPROVED** [review]
/approve

**Comment by frank-zsy** [comment]
Is this still a WIP PR?

**Comment by zhaofeng-shu33** [comment]
> Is this still a WIP PR?

Yes, there is some problems with data-format.

**Comment by frank-zsy** [comment]
OK, then I will approve this PR later.

**Comment by zhaofeng-shu33** [comment]
image

**Comment by frank-zsy** [comment]
There is a validation lambda in table schema and the default process is checking the `审核状态` column, if your table do not have this column, you just need to set the function to `() => true` just like `table_patient_detail`

**Pull request merged**
